trigger:
  branches:
    include:
      - main  # Change this to the name of your main branch, e.g., master


pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '6.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'ClassLibraryProjects.sln'  # Change this to your solution file

- task: VSBuild@1
  inputs:
    solution: 'ClassLibraryProjects.sln'  # Change this to your solution file
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'StringLibrary/StringLibrary.csproj'
    packDirectory: '$(build.artifactStagingDirectory)/nuget'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BuildVersion'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'StringLibrary/StringLibrary.csproj'
    packDirectory: '$(build.artifactStagingDirectory)/nuget'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BuildVersion'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)/nuget'
    ArtifactName: 'nuget'

- task: NuGetAuthenticate@0

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/nuget/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '<your-Azure-Artifacts-Feed-Name>'  # Replace with your Azure Artifacts Feed name
